language: node_js
cache:
    npm: false
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: kCGNEx7nqFcC4l/UWOgQInMoipcYtjWCWwTWY7YKAF7vWcj4HLu9TPFoMDCe3ji/ZE2MlFgdFIsZjaVqjh8FP9AHUrM+dJzbxTbJLZI1dzgzb4zrMLWabrgja0TAjtT2/TEiTp8LGMriQYQE9GKF0O+XKHYiFY6dxnO7PPBsRjTDkQDcIl1SUKGrRr4GmfZU5+qSg5wBst4ENmBsbvGApE7lTD8az0W1wrvxcv1KiV4ZFOtE2VWRmBII3WMCK18zZZex2WNZ0CbEvvFQYdQVMawpDtQN3XO7wiMLF8MYlKX+DVeycMeAJV+wGoW65f7P6U5odAFHcUKJKQtLzaq8A1KnwvsLWXLgeiTOM8P0y+8G4l922c27JCD6RSt4MvYtRiA1LGDUdMRpqLWqx7D09z8PxV6NsgIHXzn918nsT8Ep7AeY48wpZf3QvD3qgSH0QQJPmgR3wOU6jLWvcXPYDGaNCZQUwYx9WknyzcavGj8U3OoDLaVEu+p/vr4pPiE+WvqXhYjiZ7gpPckY6iuI/tiz+F6kvOUk1VdFIZqNRW4P0M0qzW7TwV1xv6nO4ImCIzD+CSqsiAbTpLkIVQx8hsN2F1wzBXANa3dobNISH0dJT1iE5NX7HnQxMm23f0qsPaspP2jBt8XdKN+ZKtWZN8hppWyj3YroSSuzZbpWXbQ=
